name: deploy

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                    - 6379:6379

        steps:
            - name: Checkout code
              run: echo ${{ secrets.SECRET }}

            - name: setup
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: upload-artifact
              uses: actions/upload-artifact@v3
              with:
                path: public/

    deploy:
        if: ${{ always()}}
        runs-on: ubuntu-latest
        needs: build

        steps:

            - name: Deploy to production
              run: echo "Deploying to production server..."

            