name: deploy

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              run: echo ${{ secrets.SECRET }}

            - name: setup
              uses: actions/setup-node@v4