name: deploy

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                    - 6379:6379

        steps:
            - name: Checkout code
              run: echo ${{ secrets.SECRET }}

            - name: setup
              uses: actions/setup-node@v4